# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-01 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joshua_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume_Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(max_length=100)),
                ('sur_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('telephone', models.IntegerField()),
                ('email', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('work_history', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='education_item',
            name='class_item',
        ),
        migrations.RemoveField(
            model_name='item',
            name='occupation',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='item',
        ),
        migrations.DeleteModel(
            name='Class_Item',
        ),
        migrations.DeleteModel(
            name='Education_Item',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='Resume',
        ),
        migrations.DeleteModel(
            name='Work_Item',
        ),
    ]
